# Generated by Django 5.2.7 on 2025-10-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadHistory',
            fields=[
                ('data_date', models.DateField(primary_key=True, serialize=False)),
                ('load_time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'load_history',
            },
        ),
        migrations.CreateModel(
            name='ElecReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('plan_GES', models.FloatField(blank=True, null=True)),
                ('plan_AES', models.FloatField(blank=True, null=True)),
                ('plan_TES', models.FloatField(blank=True, null=True)),
                ('plan_SES', models.FloatField(blank=True, null=True)),
                ('plan_VES', models.FloatField(blank=True, null=True)),
                ('plan_other', models.FloatField(blank=True, null=True)),
                ('techmin_GES', models.FloatField(blank=True, null=True)),
                ('techmin_AES', models.FloatField(blank=True, null=True)),
                ('techmin_TES', models.FloatField(blank=True, null=True)),
                ('techmin_SES', models.FloatField(blank=True, null=True)),
                ('techmin_VES', models.FloatField(blank=True, null=True)),
                ('techmin_other', models.FloatField(blank=True, null=True)),
                ('technomin_GES', models.FloatField(blank=True, null=True)),
                ('technomin_AES', models.FloatField(blank=True, null=True)),
                ('technomin_TES', models.FloatField(blank=True, null=True)),
                ('technomin_SES', models.FloatField(blank=True, null=True)),
                ('technomin_VES', models.FloatField(blank=True, null=True)),
                ('technomin_other', models.FloatField(blank=True, null=True)),
                ('techmax_GES', models.FloatField(blank=True, null=True)),
                ('techmax_AES', models.FloatField(blank=True, null=True)),
                ('techmax_TES', models.FloatField(blank=True, null=True)),
                ('techmax_SES', models.FloatField(blank=True, null=True)),
                ('techmax_VES', models.FloatField(blank=True, null=True)),
                ('techmax_other', models.FloatField(blank=True, null=True)),
                ('plan_consumption', models.FloatField(blank=True, null=True)),
                ('plan_export', models.FloatField(blank=True, null=True)),
                ('plan_import', models.FloatField(blank=True, null=True)),
                ('price_buy', models.FloatField(blank=True, null=True)),
                ('price_sell', models.FloatField(blank=True, null=True)),
                ('full_plan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elec_reports',
                'indexes': [models.Index(fields=['timestamp'], name='elec_report_timesta_0443a2_idx'), models.Index(fields=['region'], name='elec_report_region_26c41f_idx')],
            },
        ),
    ]
