# Generated by Django 5.2.7 on 2026-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region_id', models.IntegerField(unique=True, verbose_name='Код субъекта РФ')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование субъекта РФ')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование')),
                ('is_reported_on_ats', models.BooleanField(default=False, verbose_name='Присутствует на сайте АТС')),
                ('ats_region_name', models.CharField(blank=True, max_length=255, verbose_name='Название в АТС')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
            },
        ),
    ]
