# Generated by Django 5.2.7 on 2026-03-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_api', '0002_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveIndex(
            model_name='elecreport',
            name='elec_report_timesta_0443a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='elecreport',
            name='elec_report_region_26c41f_idx',
        ),
        migrations.AlterField(
            model_name='loadhistory',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loadhistory',
            name='load_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
